### ISSUE TITLE
Colors not all working

### ISSUE THREAD

**Issue by jljr222** [nikooo777/ckSurf#12] opened 2016-10-28 15:03 UTC
Hi,

I've noticed in my server that not all the colors are being printed correctly. I'm not sure why exactly. I've attached a screenshot.
![color-issue-1](https://cloud.githubusercontent.com/assets/3527321/19811141/2d037c8e-9cfe-11e6-8cc3-e151ac952832.png)
![color-issue-2](https://cloud.githubusercontent.com/assets/3527321/19811147/3085df14-9cfe-11e6-9d7c-41977e5d3131.png)

**Comment by Destinyg133** [comment] 2016-10-28 15:06
also when someone is potentional his rank is not printed when he is typing, altho everythig works on scoreboard

**Comment by itsthoomus** [comment] 2016-10-29 00:36
surf wizard also has the same effect as potential and i don't think purple
works either

**Comment by Caaine** [comment] 2016-10-30 22:55
{darkred}GOD   
{green}VETERAN 
{green}SURF{purple}WIZURD

:(

**Comment by nikooo777** [comment] 2016-11-08 23:52
have you verified the supported colors?
Available colors: {default}, {darkred}, {green}, {lightgreen}, {orange}, {blue}, {olive}, {lime}, {red}, {purple}, {grey}, {yellow}, {lightblue}, {steelblue}, {darkblue}, {pink}, {lightred}

and is your syntax updated? https://github.com/nikooo777/ckSurf/blob/master/csgo/addons/sourcemod/configs/ckSurf/skillgroups.cfg

**Comment by jljr222** [comment] 2016-11-08 23:56
I can confirm I am using your latest release with the latest skillgroups.cfg file provided. You can see in my screenshot from the OP that the default colors start failing at "GOD"

**Comment by nikooo777** [comment] 2016-11-09 00:33
could you please post your skillsgroup here?

**Comment by jljr222** [comment] 2016-11-09 00:35
```
//Points for skill group 2-9: percentage * (MaxPointsFromMaps
//MaxPointsFromMaps = MapCount * 700p + Bonus count * 400
//
// Max rank lenght: 32 characters
// Always keep ranks in ascending order by percentage
// Available colors: {default}, {darkred}, {green}, {lightgreen}, {orange}, {blue}, {olive}, {lime}, {red}, {purple}, {grey}, {yellow}, {lightblue}, {steelblue}, {darkblue}, {pink}, {lightred}	 
// Known issues: Orange and Purple won't work if they are at the start of the rank name

// name 		-> the text you will see as rank (can be colored with multiple colors as well)
// percentage 	-> the percent required to get that rank title
// rankColor 	-> the color the player's name will be if he/she is on that rank

"ckSurf.SkillGroups"
{
	"1"
	{
		"name"				"{DEFAULT}NEW"
		"percentage"		"-1.0"
		"rankColor"			"{DEFAULT}"
	}	
	"2"
	{
		"name"				"{GREY}SCRUB"
		"percentage"        "0.005"
		"rankColor"			"{GRAY}"
	}
	"3"
	{
		"name"				"{GREY}TRAINEE"
		"percentage"        "0.01"
		"rankColor"			"{GREY}"
	}	
	"4"
	{
		"name"				"{LIGHTBLUE}CASUAL"
		"percentage"        "0.018"
		"rankColor"			"{LIGHTBLUE}"
	}	
	"5"
	{
		"name"				"{BLUE}POTENTIAL"
		"percentage"        "0.03"
		"rankColor"			"{BLUE}"
	}	
	"6"
	{
		"name"				"{DARKBLUE}REGULAR"
		"percentage"        "0.05"
		"rankColor"			"{DARKBLUE}"
	}
	"7"
	{
		"name"				"{YELLOW}SKILLED"
		"percentage"		"0.08"
		"rankColor"			"{YELLOW}"
	}
	"8"
	{
		"name"				"{lightgreen}EXPERIENCED"
		"percentage"        "0.12"
		"rankColor"			"{lightgreen}"
	}
	"9"
	{
		"name"				"{LIME}EXPERT"
		"percentage"		"0.17"
		"rankColor"			"{LIME}"
	}
	"10"
	{
		"name"				"{PINK}SEMIPRO"
		"percentage"		"0.23"
		"rankColor"			"{PINK}"
	}
	"11"
	{
		"name"				"{LIGHTRED}PRO"
		"percentage"        "0.29"
		"rankColor"			"{LIGHTRED}"
	}
	"12"
	{
		"name"				"{RED}GODLIKE"
		"percentage"        "0.36"
		"rankColor"			"{RED}"
	}
	"13"
	{
		"name"				"{DARKRED}GOD"
		"percentage"        "0.41"
		"rankColor"			"{DARKRED}"
	}
	"14"
	{
		"name"				"{GREEN}VETERAN"
		"percentage"		"0.46"
		"rankColor"			"{GREEN}"
	}
	"15"
	{
		"name"				"{BLUE}SURF{PURPLE}WIZURD"
		"percentage"		"0.50"
		"rankColor"			"{PURPLE}"
	}
}
```

**Comment by nikooo777** [comment] 2016-11-09 01:03
that's so weird, check GODLIKE, it's supposed to be RED but it's actually green. 
Could you eventually try to switch all colors to a single one and iterate through all of them? 

I'm curious to see if there are colors that don't work at all or if some colors are just swapped (wouldn't surprise me as i'm colorblind ahahha) or if cksurf is just buggy as always.

Unfortunately I don't have much free time lately, I would do this myself but I simply can't.

**Comment by olokos** [comment] 2016-12-08 01:37
`L 12/07/2016 - 21:22:10: "[<3]#Fister®<15><STEAM_CENSOREDXXX><CT>" say "1r"
[<3]#Fister®: 1r
L 12/07/2016 - 21:22:10: [SM] Exception reported: Using two team colors in one message is not allowed
L 12/07/2016 - 21:22:10: [SM] Blaming: ckSurf.smx
L 12/07/2016 - 21:22:10: [SM] Call stack trace:
L 12/07/2016 - 21:22:10: [SM]   [0] ThrowError
L 12/07/2016 - 21:22:10: [SM]   [1] Line 425, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CFormat
L 12/07/2016 - 21:22:10: [SM]   [2] Line 219, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CPrintToChatEx
L 12/07/2016 - 21:22:10: [SM]   [3] Line 254, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CPrintToChatAllEx
L 12/07/2016 - 21:22:10: [SM]   [4] Line 301, ckSurf/hooks.sp::Say_Hook
L 12/07/2016 - 21:22:10: [SM] Exception reported: Invalid field "params" for message "CCSUsrMsg_SayText2"
L 12/07/2016 - 21:22:10: [SM] Blaming: simple-chatprocessor.smx
L 12/07/2016 - 21:22:10: [SM] Call stack trace:
L 12/07/2016 - 21:22:10: [SM]   [0] PbReadString
L 12/07/2016 - 21:22:10: [SM]   [1] Line 353, D:\Libraries\Documents\Repos\Simple Chat Processor\scripting\simple-chatprocessor.sp::OnSayText2
L 12/07/2016 - 21:22:10: [SM] Exception reported: Invalid field "params" for message "CCSUsrMsg_SayText2"
L 12/07/2016 - 21:22:10: [SM] Blaming: simple-chatprocessor.smx
L 12/07/2016 - 21:22:10: [SM] Call stack trace:
L 12/07/2016 - 21:22:10: [SM]   [0] PbReadString
L 12/07/2016 - 21:22:10: [SM]   [1] Line 353, D:\Libraries\Documents\Repos\Simple Chat Processor\scripting\simple-chatprocessor.sp::OnSayText2
L 12/07/2016 - 21:22:10: [SM] Exception reported: Invalid field "params" for message "CCSUsrMsg_SayText2"
L 12/07/2016 - 21:22:10: [SM] Blaming: simple-chatprocessor.smx
L 12/07/2016 - 21:22:10: [SM] Call stack trace:
L 12/07/2016 - 21:22:10: [SM]   [0] PbReadString
L 12/07/2016 - 21:22:10: [SM]   [1] Line 353, D:\Libraries\Documents\Repos\Simple Chat Processor\scripting\simple-chatprocessor.sp::OnSayText2
L 12/07/2016 - 21:22:10: [SM] Exception reported: Invalid field "params" for message "CCSUsrMsg_SayText2"
L 12/07/2016 - 21:22:10: [SM] Blaming: simple-chatprocessor.smx
L 12/07/2016 - 21:22:10: [SM] Call stack trace:
L 12/07/2016 - 21:22:10: [SM]   [0] PbReadString
L 12/07/2016 - 21:22:10: [SM]   [1] Line 353, D:\Libraries\Documents\Repos\Simple Chat Processor\scripting\simple-chatprocessor.sp::OnSayText2
`

I just saw this randomly in my server console, what's interesting that I couldn't reproduce it again by taping 1r myself...

**Comment by Caaine** [comment] 2017-01-11 06:05
Fix for this? :S

**Comment by nikooo777** [comment] 2017-01-11 13:33
Are you guys using sm1.8?
Sm1.9 seems to give issues of compatibility

**Comment by jljr222** [comment] 2017-01-11 13:43
My issue does not have to do with SM 1.9 because I've only been using SM 1.8

**Comment by Caaine** [comment] 2017-01-11 14:27
sm1.8

**Comment by Destinyg133** [comment] 2017-01-11 19:10
sm 1.8 aswell, we all have issue with your plugin on colours ^^

**Comment by nikooo777** [comment] 2017-01-12 16:51
Colors never were my thing, i'm discretely colorblind 😂
I will look into it, i promise

**Comment by 2called-chaos** [comment] 2017-01-12 18:02
Well if you are colorblind this might not be that helpful but with !ranks you get an overview of all the ranks and this is what it looks like for me (with the default skillgroups)...

![output of !ranks](http://i.imgur.com/02InojZ.png)

I verified (with ck_welcome_msg) that using `{red}` is indeed green. What I don't understand is why the ranks after "Godlike" have non-interpreted color tags in them.

**Comment by nikooo777** [comment] 2017-01-16 20:18
thank you for your in depth research.
It believe i used a slightly modified version of more_colors that works with CSGO.

I guess it's time to hunt down the bug!

I'll let you know

**Comment by nikooo777** [comment] 2017-01-16 22:34
So, small correction, this project is actually using smlib, i updated it just in case there was something wrong.
Next step (i'm doing it now) I'm checking the KV for the colors

**Comment by Caaine** [comment] 2017-01-17 05:33
[SM] Exception reported: Using two team colors in one message is not allowed
[SM] Blaming: ckSurf.smx
Call stack trace:
[SM]   [0] ThrowError
[SM]   [1] Line 425, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CFormat
[SM]   [2] Line 219, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CPrintToChatEx
[SM]   [3] Line 254, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CPrintToChatAllEx
[SM]   [4] Line 301, ckSurf/hooks.sp::Say_Hook

change all to:
https://forums.alliedmods.net/showthread.php?t=286913
or not working? :S

**Comment by 2called-chaos** [comment] 2017-01-17 13:51
I get this exception as well but only if I use orange with blue together. I only took a brief look at shavit's timer but it uses chat processor, I can check later whether the colors are working there or not.

**Comment by jljr222** [comment] 2017-02-01 03:16
I tried your latest commit and still the colors do not really work...

**Comment by nikooo777** [comment] 2017-02-01 11:00
As soon as i free up a couple of hours I will make the colors great again. Sorry until then

**Comment by Destinyg133** [comment] 2017-02-01 15:51
will other issues be fixed aswell?

**Comment by megazon12** [comment] 2017-02-05 16:29
when this issue will be solved?

**Comment by olokos** [comment] 2017-02-06 16:28
He just said that as soon as he frees up a couple of hours. Give him a break goddamit 😠

**Comment by lewisgranty** [comment] 2017-03-02 23:18
Is there still no solution to this @nikooo777

**Comment by Destinyg133** [comment] 2017-03-09 19:55
when in spectate colours partly work for players that type in chat,
example surfwizurd rank not shown while player is spawned but while he is in spectate colour and rank will be shown but surfwizurd will be typed in light blue

**Comment by 2called-chaos** [comment] 2017-03-10 10:06
I tried to implement colorvariables (what chat processor is using) and it seems to work:

![chat](http://imgur.com/RyzZVw4.jpg)

Well purple doesn't look really purple to me but apart from that only a few names have changed but it would be easy to add aliases for colors due to it [using a trie](https://github.com/2called-chaos/ckSurf/blob/fix_fps_issue/csgo/addons/sourcemod/scripting/include/colorvariables.inc#L971). There is just one thing I haven't fixed yet and that is the method to strip color tags so they currently show up on the scoreboard.

I hope I understood it right with SetNextAuthor and the lack of CPrintToChatAllEx...

https://github.com/2called-chaos/ckSurf/commit/48b1f3b210191e6a82d22904b78b48059f7f2871

Any comments @nikooo777 ?

**Comment by nikooo777** [comment] 2017-03-10 10:18
Interesting approach, where did you get that colorvalues include file from?

Stripping the tag is something that has to be done eventually, the way it was working till now is a bit dirty and it's the loop you commented out. 

Also, i can't remember but i think there was a reason as to why Ex was used, i need to look it up

**Comment by Destinyg133** [comment] 2017-03-10 10:21
gj! this is awesome work

**Comment by 2called-chaos** [comment] 2017-03-10 10:25
@nikooo777 I got it from here https://github.com/Drixevel/Chat-Processor/blob/master/scripting/include/colorvariables.inc

CPrintToChatAllEx is the same as CPrintToChatAll but using teamcolor of a given player (author) as far as I understood it. And this color implementation seems to introduce this SetNextAuthor approach and all the chat functions set it back to 0.

**Comment by Destinyg133** [comment] 2017-03-12 21:06
any news on realeasing?

**Comment by Destinyg133** [comment] 2017-03-16 00:06
still nothing?

**Comment by nikooo777** [comment] 2017-03-16 00:35
i'm sorry for my silence, i just don't want to drive the hype up if i already know i can't find the time just yet. Colors will not prevent players from enjoying a good surf, but i'll still do my best asap

**Comment by Destinyg133** [comment] 2017-03-16 00:40
allright, ^^

**Comment by M-archand** [comment] 2017-05-09 21:26
Don't mean to be a bother, just wondering if you've had any time to delve into this issue recently?
@2called-chaos 's fix seems to work, have you thought of implementing it into your tree? I'd try implementing it into your current files (build from 2 days ago) but I'm afraid I'd screw something up while cutting and pasting

**Comment by 2called-chaos** [comment] 2017-10-10 17:22
@M-archand Ups, I did it again ;) I'm doing a PR when I had a chance to test it a bit more but looks good to me, would you give it a try? https://github.com/2called-chaos/ckSurf/tree/fix_colors (at this point in time, based on the current master branch)

**Comment by M-archand** [comment] 2017-10-11 01:19
@2called-chaos Tested it out on 2 different server, the first being a linux test server and it made the rank colors work 100% when you type !ranks in chat, but it completely screwed chat up when you typed, made admin tag appear like 6 times then your name. Tried it on a windows server and both !ranks & chat were messed up. I'll do some more testing later.

**Comment by 2called-chaos** [comment] 2017-10-11 12:04
@M-archand I ask because I made the same mistake and took me hours to figure out: When have you last updated your cksurf translation file? Or were you already on a current version?

I'm currently have it rolled out on my production server and it seems to work fine. The only real difference I saw is that the player names itself are now purple (I assume teamcolor). What I don't understand, my screenshots above were made with the same implementation and it wasn't like this.

Either some CS:GO or sourcemod update or some of the recent changes in CK must have done this. I already saw in the code though that you can change this color to whatever you want, maybe I should change it to the yellowish color it was before (actually CT and T had blue and yellow/ocher respectively).

What do you guys think?

(ranks, player color as CT/spec)

![image](https://i.imgur.com/8KeOAkk.png)

**Comment by M-archand** [comment] 2017-10-11 23:51
I got it to work, however, name color is the same no matter what team you're on for me

**Comment by 2called-chaos** [comment] 2017-10-12 17:20
@M-archand What do you mean by differ? I added [some aliases](https://github.com/2called-chaos/ckSurf/blob/fix_colors/csgo/addons/sourcemod/scripting/include/colorvariables.inc#L996-L1001) (I guess I will also add orange->gold) to preserve compatibility. Anything I missed?

And for me the player name is purple as CT/T and gray as spectator. Since teamcolor doesn't work anymore (for whatever reason ¯\_(ツ)_/¯), we can either hardcode a specific color or do some if/else to reimplement old behaviour [here](https://github.com/nikooo777/ckSurf/blob/3dd65d6041c46c5b555cabb17f25bfd992aeb909/csgo/addons/sourcemod/scripting/ckSurf/hooks.sp#L336-L338).

Anything else before I do a PR?

**Comment by M-archand** [comment] 2017-10-12 17:33
@2called-chaos By that I mean there are different color names, like `lightblue` `olive` etc which I see you addressed in your compatibility aliases, looks like you have everything to me 👍

**Comment by 2called-chaos** [comment] 2017-10-15 11:53
@nikooo777 Any last thoughts?
@M-archand 

I pushed two more commits (one for orange=>gold) and one for a fix to revert the player name color to yellow/blue respectively (colors not exactly like before though, blue is a bit worse in contrast). My thought is just that it doesn't really matter what team you're in, right? Shall we just use a specific color, maybe just white? This only matters if you have `ck_colored_chatnames = 0` of course.

**Comment by M-archand** [comment] 2017-10-15 19:01
Yeah, I agree. I feel as though due to the nature of of this plugin, it doesn't really matter what team color you have since surf isn't team based. In my opinion having all names being white would look better, but that's just me. I tend to have names color based on ranks anyway.

**Comment by nikooo777** [comment] 2017-10-16 07:30
looks good to me! I agree on the fact that it doesn't really matter which team color one has as everyone is playing for the same objective and teams don't matter.

Great job right there! thank you for putting this effort into this issue :)

**Closed** 2017-10-18 23:25 UTC

**Comment by nikooo777** [comment] 2017-10-18 23:26
super great job again!
Merged ;)
